export const APP_ASSETS = {
    header_1 : "/assets/images/header_1.jpg",
    header_2 : "/assets/images/header_2.png",
    header_3 : "/assets/images/header_3.png",
    cover_1 : "/assets/images/cover_1.jpg",
    cover_2 : "/assets/images/cover_2.jpg",
    header : "/assets/images/header.jpeg",
    profil : "/assets/images/profil.jpg",
    background : "/assets/images/background.jpg",
    logo : "/assets/images/logo/logo.png",
    logo_long_blanc : "/assets/images/logo/logo_long_blanc.png",
    logo_long_noire : "/assets/images/logo/logo_long_noire.png",
    pdf : '/assets/files/cv.pdf',
    from_1 : "/assets/home/1.png",
    from_2 : "/assets/home/2.png",
    from_3 : "/assets/home/3.png",
    from_4 : "/assets/home/4.png",
    from_5 : "/assets/home/5.png",
    from_6 : "/assets/home/6.png"
}